### ISSUE TITLE
还没用几下 就被豆瓣反爬虫禁止掉IP了

### ISSUE THREAD

**Issue by 907739769** [muyeyong/movie_robot#2]
![屏幕截图 2022-01-31 223531](https://user-images.githubusercontent.com/27858369/151812812-654b6c3b-56cd-4784-9e17-5ba04bf3d839.png)
![屏幕截图 2022-01-31 223619](https://user-images.githubusercontent.com/27858369/151812855-c07c5844-dd95-4c12-b348-7adec458a7cc.png)

**Comment by muyeyong** [comment]
无能为力，换ip试一下
