### ISSUE TITLE
豆瓣收藏《侠探杰克》没有自动下载

### ISSUE THREAD

**Issue by 907739769** [muyeyong/movie_robot#3]
豆瓣收藏《侠探杰克》程序脚本会认为是电影，因为这个美剧豆瓣的页面没有用到“集数”关键词，建议可以加上用“单集片长”关键词

**Comment by 907739769** [comment]
match_js = re.findall(r'<span class="pl">集数:</span>\s*(\d+)<br/>', text)
        match_pc = re.findall(r'<span class="pl">单集片长:</span>\s*(\d+)分钟<br/>', text)
        if (match_js is not None and len(match_js) > 0) or (match_pc is not None and len(match_pc) > 0):
            if match_js is not None and len(match_js) > 0:
                episode = int(str(match_js[0]))
            else:
                episode = 1
            type = 'Series'

**Comment by muyeyong** [comment]
这个可以在user_config.yml自定义配置，typeMappingPath：配置对应的type 和 rootFile 映射就可以了
